# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authentication.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='authentication.proto',
  package='authentication',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x61uthentication.proto\x12\x0e\x61uthentication\x1a\x1fgoogle/protobuf/timestamp.proto\"9\n\x13\x41uthenticateRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\";\n\x11\x41uthenticateReply\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x02id\x18\x02 \x01(\x05H\x00\x88\x01\x01\x42\x05\n\x03_id\"(\n\x0c\x42usinessArea\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\"\xa9\x01\n\x13RegistrationRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12/\n\x0b\x64\x61teofbirth\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\x12\x32\n\x0c\x62usinessarea\x18\x06 \x01(\x0b\x32\x1c.authentication.BusinessArea\"I\n\x11RegistrationReply\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x16\n\taccountId\x18\x02 \x01(\x03H\x00\x88\x01\x01\x42\x0c\n\n_accountId2\xbe\x01\n\x0c\x41uthenticate\x12R\n\x08TryLogin\x12#.authentication.AuthenticateRequest\x1a!.authentication.AuthenticateReply\x12Z\n\x10UserRegistration\x12#.authentication.RegistrationRequest\x1a!.authentication.RegistrationReplyb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_AUTHENTICATEREQUEST = _descriptor.Descriptor(
  name='AuthenticateRequest',
  full_name='authentication.AuthenticateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='authentication.AuthenticateRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='authentication.AuthenticateRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=130,
)


_AUTHENTICATEREPLY = _descriptor.Descriptor(
  name='AuthenticateReply',
  full_name='authentication.AuthenticateReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='authentication.AuthenticateReply.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='authentication.AuthenticateReply.id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_id', full_name='authentication.AuthenticateReply._id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=132,
  serialized_end=191,
)


_BUSINESSAREA = _descriptor.Descriptor(
  name='BusinessArea',
  full_name='authentication.BusinessArea',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='authentication.BusinessArea.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='authentication.BusinessArea.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=233,
)


_REGISTRATIONREQUEST = _descriptor.Descriptor(
  name='RegistrationRequest',
  full_name='authentication.RegistrationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='authentication.RegistrationRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dateofbirth', full_name='authentication.RegistrationRequest.dateofbirth', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='email', full_name='authentication.RegistrationRequest.email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='authentication.RegistrationRequest.password', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='businessarea', full_name='authentication.RegistrationRequest.businessarea', index=4,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=405,
)


_REGISTRATIONREPLY = _descriptor.Descriptor(
  name='RegistrationReply',
  full_name='authentication.RegistrationReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='authentication.RegistrationReply.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='accountId', full_name='authentication.RegistrationReply.accountId', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_accountId', full_name='authentication.RegistrationReply._accountId',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=407,
  serialized_end=480,
)

_AUTHENTICATEREPLY.oneofs_by_name['_id'].fields.append(
  _AUTHENTICATEREPLY.fields_by_name['id'])
_AUTHENTICATEREPLY.fields_by_name['id'].containing_oneof = _AUTHENTICATEREPLY.oneofs_by_name['_id']
_REGISTRATIONREQUEST.fields_by_name['dateofbirth'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_REGISTRATIONREQUEST.fields_by_name['businessarea'].message_type = _BUSINESSAREA
_REGISTRATIONREPLY.oneofs_by_name['_accountId'].fields.append(
  _REGISTRATIONREPLY.fields_by_name['accountId'])
_REGISTRATIONREPLY.fields_by_name['accountId'].containing_oneof = _REGISTRATIONREPLY.oneofs_by_name['_accountId']
DESCRIPTOR.message_types_by_name['AuthenticateRequest'] = _AUTHENTICATEREQUEST
DESCRIPTOR.message_types_by_name['AuthenticateReply'] = _AUTHENTICATEREPLY
DESCRIPTOR.message_types_by_name['BusinessArea'] = _BUSINESSAREA
DESCRIPTOR.message_types_by_name['RegistrationRequest'] = _REGISTRATIONREQUEST
DESCRIPTOR.message_types_by_name['RegistrationReply'] = _REGISTRATIONREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AuthenticateRequest = _reflection.GeneratedProtocolMessageType('AuthenticateRequest', (_message.Message,), {
  'DESCRIPTOR' : _AUTHENTICATEREQUEST,
  '__module__' : 'authentication_pb2'
  # @@protoc_insertion_point(class_scope:authentication.AuthenticateRequest)
  })
_sym_db.RegisterMessage(AuthenticateRequest)

AuthenticateReply = _reflection.GeneratedProtocolMessageType('AuthenticateReply', (_message.Message,), {
  'DESCRIPTOR' : _AUTHENTICATEREPLY,
  '__module__' : 'authentication_pb2'
  # @@protoc_insertion_point(class_scope:authentication.AuthenticateReply)
  })
_sym_db.RegisterMessage(AuthenticateReply)

BusinessArea = _reflection.GeneratedProtocolMessageType('BusinessArea', (_message.Message,), {
  'DESCRIPTOR' : _BUSINESSAREA,
  '__module__' : 'authentication_pb2'
  # @@protoc_insertion_point(class_scope:authentication.BusinessArea)
  })
_sym_db.RegisterMessage(BusinessArea)

RegistrationRequest = _reflection.GeneratedProtocolMessageType('RegistrationRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTRATIONREQUEST,
  '__module__' : 'authentication_pb2'
  # @@protoc_insertion_point(class_scope:authentication.RegistrationRequest)
  })
_sym_db.RegisterMessage(RegistrationRequest)

RegistrationReply = _reflection.GeneratedProtocolMessageType('RegistrationReply', (_message.Message,), {
  'DESCRIPTOR' : _REGISTRATIONREPLY,
  '__module__' : 'authentication_pb2'
  # @@protoc_insertion_point(class_scope:authentication.RegistrationReply)
  })
_sym_db.RegisterMessage(RegistrationReply)



_AUTHENTICATE = _descriptor.ServiceDescriptor(
  name='Authenticate',
  full_name='authentication.Authenticate',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=483,
  serialized_end=673,
  methods=[
  _descriptor.MethodDescriptor(
    name='TryLogin',
    full_name='authentication.Authenticate.TryLogin',
    index=0,
    containing_service=None,
    input_type=_AUTHENTICATEREQUEST,
    output_type=_AUTHENTICATEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UserRegistration',
    full_name='authentication.Authenticate.UserRegistration',
    index=1,
    containing_service=None,
    input_type=_REGISTRATIONREQUEST,
    output_type=_REGISTRATIONREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUTHENTICATE)

DESCRIPTOR.services_by_name['Authenticate'] = _AUTHENTICATE

# @@protoc_insertion_point(module_scope)
