# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import authentication_pb2 as authentication__pb2


class AuthenticateStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TryLogin = channel.unary_unary(
                '/authentication.Authenticate/TryLogin',
                request_serializer=authentication__pb2.AuthenticateRequest.SerializeToString,
                response_deserializer=authentication__pb2.AuthenticateReply.FromString,
                )


class AuthenticateServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TryLogin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthenticateServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TryLogin': grpc.unary_unary_rpc_method_handler(
                    servicer.TryLogin,
                    request_deserializer=authentication__pb2.AuthenticateRequest.FromString,
                    response_serializer=authentication__pb2.AuthenticateReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'authentication.Authenticate', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Authenticate(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TryLogin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/authentication.Authenticate/TryLogin',
            authentication__pb2.AuthenticateRequest.SerializeToString,
            authentication__pb2.AuthenticateReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
